version: "3.8"

services:
  php:
    build:
      context: ./server
    container_name: php_server
    expose:
      - "80"
    volumes:
      - ./server:/var/www/html
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql/mysql-server:8.0
    container_name: mysql_server
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
      - ./server/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped

  client:
    build:
      context: ./client
    container_name: nextjs_client
    expose:
      - "3000"
    volumes:
      - ./client:/app
    working_dir: /app
    command: "npm run dev"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    depends_on:
      - client
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

volumes:
  db_data:
